<!DOCTYPE html>
<!-- saved from url=(0079)https://code.qt.io/cgit/qt/qtwebchannel.git/plain/src/javascript/qwebchannel.js -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>qt/qtwebchannel.git - Qt WebChannel
</title>
<meta name="generator" content="cgit v1.2.3">
<meta name="robots" content="index, nofollow">
<link rel="stylesheet" type="text/css" href="./qwebchannel_files/cgit.css">
<link rel="shortcut icon" href="https://code.qt.io/favicon.ico">
<link rel="alternate" title="Atom feed" href="https://code.qt.io/cgit/qt/qtwebchannel.git/atom/?h=dev" type="application/atom+xml">
<link rel="vcs-git" href="git://code.qt.io/qt/qtwebchannel.git" title="qt/qtwebchannel.git Git repository">
<link rel="vcs-git" href="http://code.qt.io/qt/qtwebchannel.git" title="qt/qtwebchannel.git Git repository">
<link rel="vcs-git" href="https://code.qt.io/qt/qtwebchannel.git" title="qt/qtwebchannel.git Git repository">
</head>
<body>
<div id="cgit"><table id="header">
<tbody><tr>
<td class="logo" rowspan="2"><a href="https://code.qt.io/cgit/"><img src="./qwebchannel_files/logo_qt.png" alt="cgit logo"></a></td>
<td class="main"><a href="https://code.qt.io/cgit/">index</a> : <a title="qt/qtwebchannel.git" href="https://code.qt.io/cgit/qt/qtwebchannel.git/">qt/qtwebchannel.git</a></td><td class="form"><form method="get">
<select name="h" onchange="this.form.submit();">
<option value="5.10">5.10</option>
<option value="5.11">5.11</option>
<option value="5.12">5.12</option>
<option value="5.13">5.13</option>
<option value="5.14">5.14</option>
<option value="5.15">5.15</option>
<option value="5.4">5.4</option>
<option value="5.5">5.5</option>
<option value="5.6">5.6</option>
<option value="5.7">5.7</option>
<option value="5.8">5.8</option>
<option value="5.9">5.9</option>
<option value="6.2">6.2</option>
<option value="6.2.0">6.2.0</option>
<option value="6.2.4">6.2.4</option>
<option value="6.3">6.3</option>
<option value="6.4">6.4</option>
<option value="6.4.0">6.4.0</option>
<option value="6.4.1">6.4.1</option>
<option value="6.4.2">6.4.2</option>
<option value="6.4.3">6.4.3</option>
<option value="6.5">6.5</option>
<option value="6.5.0">6.5.0</option>
<option value="6.5.1">6.5.1</option>
<option value="6.5.2">6.5.2</option>
<option value="6.5.3">6.5.3</option>
<option value="6.6">6.6</option>
<option value="6.6.0">6.6.0</option>
<option value="6.6.1">6.6.1</option>
<option value="6.6.2">6.6.2</option>
<option value="6.6.3">6.6.3</option>
<option value="6.7">6.7</option>
<option value="6.7.0">6.7.0</option>
<option value="6.7.1">6.7.1</option>
<option value="6.7.2">6.7.2</option>
<option value="6.7.3">6.7.3</option>
<option value="6.8">6.8</option>
<option value="6.8.0">6.8.0</option>
<option value="6.8.1">6.8.1</option>
<option value="6.8.2">6.8.2</option>
<option value="6.9">6.9</option>
<option value="dev" selected="selected">dev</option>
<option value="wip/cmake">wip/cmake</option>
</select> <input type="submit" value="switch"></form></td></tr>
<tr><td class="sub">Qt WebChannel
</td><td class="sub right"></td></tr></tbody></table>
<table class="tabs"><tbody><tr><td>
<a href="https://code.qt.io/cgit/qt/qtwebchannel.git/about/">about</a><a href="https://code.qt.io/cgit/qt/qtwebchannel.git/">summary</a><a href="https://code.qt.io/cgit/qt/qtwebchannel.git/refs/">refs</a><a href="https://code.qt.io/cgit/qt/qtwebchannel.git/log/">log</a><a href="https://code.qt.io/cgit/qt/qtwebchannel.git/tree/">tree</a><a href="https://code.qt.io/cgit/qt/qtwebchannel.git/commit/">commit</a><a href="https://code.qt.io/cgit/qt/qtwebchannel.git/diff/">diff</a><a href="https://code.qt.io/cgit/qt/qtwebchannel.git/stats/">stats</a></td><td class="form"><form class="right" method="get" action="https://code.qt.io/cgit/qt/qtwebchannel.git/log/">
<select name="qt">
<option value="grep">log msg</option>
<option value="author">author</option>
<option value="committer">committer</option>
<option value="range">range</option>
</select>
<input class="txt" type="search" size="10" name="q" value="">
<input type="submit" value="search">
</form>
</td></tr></tbody></table>
<div class="content"><div class="error">Not found</div>
</div> <!-- class=content -->
<div class="footer">generated by <a href="https://git.zx2c4.com/cgit/about/">cgit v1.2.3</a> (<a href="https://git-scm.com/">git 2.25.1</a>) at 2025-02-14 04:48:05 +0000</div>
</div> <!-- id=cgit -->


</body></html>